name: librarian-dev
channels:
- anjos
- defaults
dependencies:
- python=3.6
- six
- docopt
- guessit
- mutagen
- tmdbsimple
- pytvdbapi
- ffmpeg
- subliminal
- ipdb
- zc.buildout
- nose
- sphinx
- coverage
- pexpect
- tqdm
- chardet
- babelfish
