name: librarian-dev
channels:
- anjos
- defaults
dependencies:
- python=3.6
- docopt
- guessit
- mutagen
- qtfaststart
- tmdbsimple
- tvdbapi-client
- ffmpeg-python
- subliminal
- ipdb
- zc.buildout
- nose
- sphinx
- coverage
