{% set name = "tvdbapi-client" %}
{% set pyname = "tvdbapi_client" %}
{% set version = "0.1.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pyname[0] }}/{{ pyname }}/{{ pyname }}-{{ version }}.tar.gz
  md5: 803a13ae202c11204e368b392c97eb93

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - pbr
    - twine

  run:
    - python
    - pbr
    - twine

test:
  imports:
    - {{ pyname }}

about:
  home: https://github.com/shad7/tvdbapi_client
  license: MIT
  summary: 'Python client for theTVDB API (v1.2+) REST endpoints in json format'

extra:
  recipe-maintainers:
    - anjos
