{% set version = "2.0.5" %}

package:
  name: subliminal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/subliminal/subliminal-{{ version }}.tar.gz
  md5: 77064c09b82609cdeac75df1cd9a55b2

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - requests

  run:
    - python
    - guessit>=2.0.1
    - babelfish>=0.5.2
    - beautifulsoup4>=4.4.0
    - requests>=2.0
    - click>=4.0
    - six>=1.9.0
    - appdirs>=1.3
    - pytz>=2012c
    - chardet>=2.3.0
    - stevedore>=1.0.0

    - enzyme>=0.4.1
    - dogpile.cache>=0.6.0
    - pysrt>=1.0.1
    - rarfile>=2.7

test:
  requires:
    - nose

  imports:
    - subliminal

  commands:
    - nosetests

about:
  home: https://github.com/Diaoul/subliminal
  license: MIT
  summary: 'Subliminal - Subtitles, faster than your thoughts'

extra:
  recipe-maintainers:
    - anjos
