{% set name = "qtfaststart" %}
{% set version = "1.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 707946a462f01c02de866ccb05b89345

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt

  entry_points:
    - qtfaststart = qtfaststart.command:run

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:

  imports:
    - {{ name }}

  commands:
    - {{ name }} --help

about:
  home: https://github.com/gtaylor/qtfaststart
  license: MIT
  summary: 'Quicktime atom positioning in Python for fast streaming'

extra:
  recipe-maintainers:
    - anjos
