{% set name="librarian" %}
{% set version="0.0.1a0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - retag_movie.py = librarian.scripts.retag_movie:main
    - retag_tvshow.py = librarian.scripts.retag_tvshow:main
  script_env:
    - TMDB_APIKEY
    - TVDB_APIKEY

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - setuptools
    - docopt
    - guessit
    - subliminal
    - mutagen
    - tmdbsimple
    - pytvdbapi
    - ffmpeg
    - pexpect
    - tqdm
    - chardet
    - babelfish
    - pysrt

test:
  imports:
    - {{ name }}

  requires:
    - nose
    - coverage

  commands:
    - getsubs.py --help
    - tomp4.py --help
    - retag_movie.py --help
    - retag_tvshow.py --help
    - nosetests -sv --with-coverage --cover-package={{ name }} {{ name }}

about:
  home: https://github.com/anjos/librarian
  license: GPLv3
  summary: Utilities for organizing Movie/TV show libraries
  license_family: GPL
