{% set name = "x264" %}
{% set version = "20170708" %}

package:
  name: x264
  version: {{ version }}

source:
  url: http://download.videolan.org/pub/videolan/{{ name }}/snapshots/{{ name }}-snapshot-{{ version }}-2245-stable.tar.bz2
  md5: 28ac1befd423c504f0d502a9d6fdce18

build:
  number: 1
  skip: true         # [win]

requirements:
  build:
    - yasm

test:
  commands:
    - test -f ${PREFIX}/include/x264.h         # [unix]
    - test -f ${PREFIX}/lib/libx264.a          # [unix]
    - test -f ${PREFIX}/lib/libx264.dylib      # [osx]
    - test -f ${PREFIX}/lib/libx264.so         # [linux]
    - x264 --help                              # [unix]

about:
  home: http://www.videolan.org/developers/x264.html
  license: GPL 2
  license_file: COPYING
  summary: A free software library for encoding video streams into the H.264/MPEG-4 AVC format.

extra:
  recipe-maintainers:
    - jakirkham
    - 183amir
    - anjos
