{% set version = "1.3.0" %}

package:
  name: yasm
  version: {{ version }}

source:
  fn: yasm-{{ version }}.tar.gz
  url: http://www.tortall.net/projects/yasm/releases/yasm-{{ version }}.tar.gz
  sha1: b7574e9f0826bedef975d64d3825f75fbaeef55e

build:
  number: 0
  skip: true  # [(unix and py3k) or (win and py36)]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]
    - vc14    # [win and py36]

requirements:
  build:
    - cmake   # [win]
    - python

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]

  commands:
    - test -f ${PREFIX}/lib/libyasm.a              # [unix]
    - if not exist %LIBRARY_LIB%\\yasm.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\yasm.dll exit 1  # [win]
    - vsyasm --help
    - yasm --help
    - ytasm /h
    - yasm --version

about:
  home: http://www.tortall.net/projects/yasm/
  license: BSD 3-Clause
  summary: 'Yasm is a complete rewrite of the NASM assembler under the "new" BSD License.'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - patricksnape
