{% set name = "tmdbsimple" %}
{% set version = "1.7.0" %}

package:
  name: tmdbsimple
  version: {{ version }}

source:
  git_url: https://github.com/celiao/tmdbsimple.git
  git_rev: {{ version }}

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - requests

  run:
    - python
    - requests
    - pyopenssl >0.14.0
    - idna >2.0.0
    - cryptography >1.3.4

test:
  requires:
    - nose
    - coverage

  imports:
    - {{ name }}

  source_files:
    - tests/*.py

  commands:
    - echo "API_KEY = {{ environ['TMDB_APIKEY'] }}" > tests/keys.py
    - nosetests -sv --with-coverage --cover-package={{ name }} {{ name }}

about:
  home: https://github.com/celiao/tmdbsimple
  license_family: GPL
  license: GPLv3
  summary: 'A wrapper for The Movie Database API v3'

extra:
  recipe-maintainers:
    - anjos
