{% set name = "ffmpeg-python" %}
{% set version = "0.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 8f56423aea3a32f35d6d194188774f5c

build:
  noarch: python
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner

  run:
    - python
    - ffmpeg
    - future

test:
  requires:
    - nose
    - coverage
    - pytest

  imports:
    - ffmpeg

  commands:
    - nosetests -sv --with-coverage --cover-package=ffmpeg ffmpeg

about:
  home: https://github.com/kkroening/ffmpeg-python
  license_family: Apache
  license: Apache Software License
  summary: 'Python bindings for FFmpeg - with complex filtering support'

extra:
  recipe-maintainers:
    - anjos
